
---
_tungsten_fabric_destdir: /opt/tungstenfabric

_tf_pod_cidr: 10.32.0.0/12
_tf_service_cidr: 10.96.0.0/12
_tf_ip_fabric_cidr: 10.32.0.0/12

_tf_controller_ip: 192.168.122.9

# let it auto pick if you cannot define
_tf_phy_intf: ""

# by default use tungsten fabric docker hub images
_tf_docker_registry: "tungstenfabric"
_tf_container_tag: "R2011-2021-01-29"


# override kube-manager container image
_tf_override_kube_manager_image: "psethi/contrail-kubernetes-kube-manager:R2011-2021-01-29-patched"

# override vrouter-kernel-init container image
_tf_override_vrouter_init_image: "psethi/contrail-vrouter-kernel-build-init:R2011-2021-01-29-patched"
